---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: homelab
  labels:
    app: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
        - name: bazarr
          image: lscr.io/linuxserver/bazarr:latest
          env:
            - name: PUID
              value: "${PUID}"
            - name: PGID
              value: "${PGID}"
            - name: TZ
              value: "${TZ}"
          ports:
            - containerPort: 6767
          volumeMounts:
            - name: bazarr-config
              mountPath: /config
            - name: media
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /
              port: 6767
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: bazarr-config
          persistentVolumeClaim:
            claimName: bazarr-config-pvc
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: homelab
spec:
  selector:
    app: bazarr
  type: NodePort
  ports:
    - port: 6767
      targetPort: 6767
      nodePort: 30767
